### ISSUE TITLE
Have the arxiv paper?

### ISSUE THREAD

**Issue by dengxiongshi** [liushh39/AGMFusion#1]
@liushh39 Hello! Have the origin paper?

**Comment by liushh39** [comment]
sorry, we don't have the arxiv paper, we will upload it as soon as possible.








 ----------Reply to Message----------
 On Mon, Aug 12, 2024 18:17 PM ***@***.***&gt; wrote:

  

 
@liushh39 Hello! Have the origin paper?

**Comment by liushh39** [comment]
or you can contact me to obtain the origin paper

**Comment by dengxiongshi** [comment]
> or you can contact me to obtain the origin paper

😄

**Comment by liushh39** [comment]
I have sent to your email, please check.

**Comment by liushh39** [comment]
We released the paper on [arXiv](https://www.techrxiv.org/users/813809/articles/1215064-agmfusion-a-real-time-end-to-end-infrared-and-visible-image-fusion-network-based-on-adaptive-guidance-module).
