### ISSUE TITLE
数据集下载不了

### ISSUE THREAD

**Issue by JAWILU** [liushh39/AGMFusion#3]
可以重新更新下链接吗？谢谢

**Comment by liushh39** [comment]
链接: https://pan.baidu.com/s/1GqxXMHKGudMJT0IsqMmQ3w?pwd=8zki 提取码: 8zki








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年12月10日(周二) 下午2:48写道:

  

 
可以重新更新下链接吗？谢谢

**Comment by JAWILU** [comment]
谢谢

**Comment by JAWILU** [comment]
感谢您数据集的分享，麻烦您看下img2文件内320307是不是有损坏？另外跑了前几次，引导损失一直为0正常吗？

**Comment by liushh39** [comment]
麻烦可以看下论文，第一个epoch没有引导损失，没有损坏








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年12月11日(周三) 下午2:33写道:

  

 
感谢您数据集的分享，麻烦您看下img2文件内320307是不是有损坏？另外跑了前几次，引导损失一直为0正常吗？

**Comment by JAWILU** [comment]
好的谢谢，建议更换一下img2的文件内32072.png图片，好像确实破损了

**Comment by JAWILU** [comment]
以及img2的1421.png，十分感谢您的分享，希望在其他人复现时能提供帮助！

**Comment by liushh39** [comment]
麻烦看下论文，img2在训练自动替换，所以它全白是无所谓的，谢谢








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年12月11日(周三) 下午3:08写道:

  

 
以及img2的1421.png，十分感谢您的分享，希望在其他人复现时能提供帮助！

**Comment by JAWILU** [comment]
不好意思，可能我表述不清楚，您分享的img2文件内上述两个png图片，Image.open打不开，训练时会报错显示找不到，劳烦确认一下谢谢！

**Comment by liushh39** [comment]
直接把img1复制命名为img2也行








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年12月11日(周三) 下午4:14写道:

  

 
不好意思，可能我表述不清楚，您分享的img2文件内上述两个png图片，Image.open打不开，训练时会报错显示找不到，劳烦确认一下谢谢！
